swagger: "2.0"
info:
  title: ecommerce-api
  version: 1.0.0
basePath: /api
tags:
  - name: category
    description: Category operations

  - name: product
    description: Product operations

  - name: auth
    description: Authentication operations

paths:
  /categories:
    post:
      summary: Create a new category
      description: Create a new category with a name and an optional parent ID.
      tags:
        - category
      parameters:
        - in: body
          name: category
          description: Category object
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                maxLength: 20
                description: The name of the category.
              parentId:
                type: integer
                format: int64
                description: The ID of the parent category (optional).
      responses:
        201:
          description: Category created successfully
        400:
          description: Bad request
        500:
          description: Internal server error

    get:
      summary: Get a list of categories
      description: Retrieve a list of all categories.
      tags:
        - category
      responses:
        200:
          description: Successful response
        500:
          description: Internal server error

  /categories/{id}:
    get:
      summary: Get a category
      description: Retrieve a category by ID.
      tags:
        - category
      parameters:
        - in: path
          name: id
          description: The ID of the category to retrieve.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
        404:
          description: Category not found
        500:
          description: Internal server error

    put:
      summary: Update a category
      description: Update a category by ID.
      tags:
        - category
      parameters:
        - in: path
          name: id
          description: The ID of the category to update.
          required: true
          type: integer
          format: int64
        - in: body
          name: category
          description: Category object
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                maxLength: 20
                description: The name of the category.
              parentId:
                type: integer
                format: int64
                description: The ID of the parent category (optional).
      responses:
        200:
          description: Category updated successfully
        400:
          description: Bad request
        404:
          description: Category not found
        500:
          description: Internal server error

    delete:
      summary: Delete a category
      description: Delete a category by ID.
      tags:
        - category
      parameters:
        - in: path
          name: id
          description: The ID of the category to delete.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Category deleted successfully
        404:
          description: Category not found
        500:
          description: Internal server error

  /products:
    post:
      summary: Create a new product
      description: Create a new product with a name, description, price, and category ID.
      tags:
        - product
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: name
          type: string
          maxLength: 20
          description: The name of the product.
        - in: formData
          name: description
          type: string
          maxLength: 100
          description: The description of the product.
        - in: formData
          name: price
          type: number
          format: double
          description: The price of the product.
        - in: formData
          name: categoryId
          type: integer
          format: int64
          description: The ID of the category.
        - in: formData
          name: image
          type: file
          format: binary
          description: The image of the product.
      responses:
      201:
        description: Product created successfully
      400:
        description: Bad request
      500:
        description: Internal server error

    get:
      summary: Get a list of products
      description: Retrieve a list of all products.
      tags:
        - product
      responses:
        200:
          description: Successful response
        500:
          description: Internal server error

  /products/{id}:
    get:
      summary: Get a product
      description: Retrieve a product by ID.
      tags:
        - product
      parameters:
        - in: path
          name: id
          description: The ID of the product to retrieve.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response
        404:
          description: Product not found
        500:
          description: Internal server error

    put:
      summary: Update a product
      description: Update a product by ID.
      tags:
        - product
      parameters:
        - in: path
          name: id
          description: The ID of the product to update.
          required: true
          type: integer
          format: int64
        - in: body
          name: product
          description: Product object
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                maxLength: 20
                description: The name of the product.
              description:
                type: string
                maxLength: 100
                description: The description of the product.
              price:
                type: number
                format: double
                description: The price of the product.
              categoryId:
                type: integer
                format: int64
                description: The ID of the category.
      responses:
        200:
          description: Product updated successfully
        400:
          description: Bad request
        404:
          description: Product not found
        500:
          description: Internal server error

    delete:
      summary: Delete a product
      description: Delete a product by ID.
      tags:
        - product
      parameters:
        - in: path
          name: id
          description: The ID of the product to delete.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Product deleted successfully
        404:
          description: Product not found
        500:
          description: Internal server error

  /auth/login:
    post:
      summary: Login
      description: Login with a username and password.
      tags:
        - auth
      parameters:
        - in: body
          name: credentials
          description: Credentials object
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                maxLength: 50
                description: The email.
              password:
                type: string
                maxLength: 20
                description: The password.
      responses:
        200:
          description: Successful response
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /auth/register:
    post:
      summary: Register
      description: Register with a username, password, and email.
      tags:
        - auth
      parameters:
        - in: body
          name: credentials
          description: Credentials object
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                maxLength: 20
                description: The name.
              password:
                type: string
                maxLength: 20
                description: The password.
              email:
                type: string
                maxLength: 50
                description: The email.
      responses:
        201:
          description: Successful response
        400:
          description: Bad request
        500:
          description: Internal server error

  /auth/create-reset-password-token:
    post:
      summary: Create reset password token
      description: Create a reset password token with an email.
      tags:
        - auth
      parameters:
        - in: body
          name: email
          description: Email object
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                maxLength: 50
                description: The email.
      responses:
        200:
          description: Successful response
        400:
          description: Bad request
        500:
          description: Internal server error

  /auth/reset-password:
    post:
      summary: Reset password
      description: Reset the password with a token and a new password.
      tags:
        - auth
      parameters:
        - in: body
          name: credentials
          description: Credentials object
          required: true
          schema:
            type: object
            properties:
              token:
                type: string
                maxLength: 50
                description: The token.
              password:
                type: string
                maxLength: 20
                description: The password.
      responses:
        200:
          description: Successful response
        400:
          description: Bad request
        500:
          description: Internal server error
